// Writes supabase/schema.sql's text to stdout from two `pg_dump
// --schema-only` files of run.sh's: one of a database with only the
// stand-ins for Supabase's own parts (stubs.sql), one of the same after
// every migration. What the migrations made is what the second has and
// the first doesn't; pg_dump writes each object as a block under a
// "-- Name: …; Type: …" heading, so blocks found in both are left out.
// That keeps what the migrations add to Supabase's parts (the trigger on
// auth.users, the tables put in the supabase_realtime publication) and
// drops the stand-ins themselves.
//
// Usage: node supabase/tests/schema.mjs <stubs dump> <migrated dump>
import { readFileSync } from 'node:fs';

const [stubsFile, migratedFile] = process.argv.slice(2);
if (!stubsFile || !migratedFile) {
  console.error('Usage: node supabase/tests/schema.mjs <stubs dump> <migrated dump>');
  process.exit(2);
}

/**
 * The dump's lines without what varies from one pg_dump to another: the
 * \restrict key, the versions, and `transaction_timeout`, which only
 * Postgres 17 knows (the file is loaded into older servers too).
 */
const lines = (file) =>
  readFileSync(file, 'utf8')
    .split('\n')
    .filter((line) => !/^\\(un)?restrict |^-- Dumped (from|by) |^SET transaction_timeout /.test(line));

/** The preamble (before the first object), then each object's block. */
function blocks(file) {
  const all = lines(file);
  const out = [];
  let current = [];
  for (let i = 0; i < all.length; i++) {
    if (all[i] === '--' && /^-- (Data for )?Name: /.test(all[i + 1] ?? '')) {
      out.push(current);
      current = [];
    }
    current.push(all[i]);
  }
  out.push(current);
  return out.map((block) => block.join('\n'));
}

// A block's identity: its text without the SET lines pg_dump puts between
// objects, which belong to wherever they fall.
const key = (block) =>
  block
    .split('\n')
    .filter((line) => !line.startsWith('SET '))
    .join('\n')
    .trim();

const stubs = new Set(blocks(stubsFile).slice(1).map(key));
const [preamble, ...objects] = blocks(migratedFile);
const kept = objects.filter((block) => !stubs.has(key(block)));

const header = `-- GENERATED by \`npm run db:generate\` from supabase/migrations: don't edit.
--
-- The whole database as the migrations leave it, to read: pg_dump's
-- --schema-only of a database made by applying every migration in order,
-- less the stand-ins for Supabase's own parts (auth, storage, pg_net).
-- A new project isn't made from this file but with \`supabase db push\`,
-- and the rows the migrations seed (chat rooms, the music library) are
-- in the migrations. \`npm run test:db\` fails when this is out of date.
`;

process.stdout.write(
  `${header}\n${[preamble.replace(/^--\n-- PostgreSQL database dump\n--\n\n/, ''), ...kept]
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()}\n`
);
