// GENERATED by `npm run db:generate` from supabase/migrations (with
// `supabase gen types`): don't edit. `npm run test:db` fails when it's out
// of date. The types of every table, view and function the API serves.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      albums: {
        Row: {
          added_at: string;
          artist: string;
          cover: string;
          note: string | null;
          title: string;
          year: number;
        };
        Insert: {
          added_at?: string;
          artist: string;
          cover: string;
          note?: string | null;
          title: string;
          year: number;
        };
        Update: {
          added_at?: string;
          artist?: string;
          cover?: string;
          note?: string | null;
          title?: string;
          year?: number;
        };
        Relationships: [];
      };
      chat_messages: {
        Row: {
          body: string;
          created_at: string;
          hidden: boolean;
          id: number;
          room: string;
          user_id: string;
        };
        Insert: {
          body: string;
          created_at?: string;
          hidden?: boolean;
          id?: never;
          room?: string;
          user_id?: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          hidden?: boolean;
          id?: never;
          room?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "chat_messages_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      chat_rooms: {
        Row: {
          created_at: string;
          id: string;
          name: string;
          position: number;
          topic: string;
        };
        Insert: {
          created_at?: string;
          id: string;
          name: string;
          position?: number;
          topic?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
          position?: number;
          topic?: string;
        };
        Relationships: [];
      };
      diary: {
        Row: {
          body: string;
          created_at: string;
          day: string;
          id: string;
          telegram_message_id: number | null;
          updated_at: string;
          version: number;
        };
        Insert: {
          body: string;
          created_at?: string;
          day: string;
          id?: string;
          telegram_message_id?: number | null;
          updated_at?: string;
          version?: number;
        };
        Update: {
          body?: string;
          created_at?: string;
          day?: string;
          id?: string;
          telegram_message_id?: number | null;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      discs: {
        Row: {
          added_at: string;
          artist: string | null;
          cover: string;
          cover_x: number;
          duration_ms: number | null;
          id: string;
          title: string;
        };
        Insert: {
          added_at?: string;
          artist?: string | null;
          cover?: string;
          cover_x?: number;
          duration_ms?: number | null;
          id: string;
          title: string;
        };
        Update: {
          added_at?: string;
          artist?: string | null;
          cover?: string;
          cover_x?: number;
          duration_ms?: number | null;
          id?: string;
          title?: string;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          body: string;
          created_at: string;
          folder: string;
          id: string;
          name: string;
          telegram_message_id: number | null;
          updated_at: string;
          version: number;
        };
        Insert: {
          body?: string;
          created_at?: string;
          folder: string;
          id?: string;
          name: string;
          telegram_message_id?: number | null;
          updated_at?: string;
          version?: number;
        };
        Update: {
          body?: string;
          created_at?: string;
          folder?: string;
          id?: string;
          name?: string;
          telegram_message_id?: number | null;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      events: {
        Row: {
          calendar: string;
          created_at: string;
          day: string;
          ends: number | null;
          id: string;
          notes: string;
          starts: number | null;
          title: string;
          updated_at: string;
          user_id: string;
          version: number;
        };
        Insert: {
          calendar?: string;
          created_at?: string;
          day: string;
          ends?: number | null;
          id?: string;
          notes?: string;
          starts?: number | null;
          title: string;
          updated_at?: string;
          user_id?: string;
          version?: number;
        };
        Update: {
          calendar?: string;
          created_at?: string;
          day?: string;
          ends?: number | null;
          id?: string;
          notes?: string;
          starts?: number | null;
          title?: string;
          updated_at?: string;
          user_id?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "events_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      job_applications: {
        Row: {
          applied_on: string;
          company: string;
          created_at: string;
          id: string;
          location: string;
          notes: string;
          outcome: string | null;
          posting: string;
          reached: string;
          role: string;
          source: string;
          stage: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          applied_on?: string;
          company: string;
          created_at?: string;
          id?: string;
          location?: string;
          notes?: string;
          outcome?: string | null;
          posting?: string;
          reached?: string;
          role?: string;
          source?: string;
          stage?: string;
          updated_at?: string;
          version?: number;
        };
        Update: {
          applied_on?: string;
          company?: string;
          created_at?: string;
          id?: string;
          location?: string;
          notes?: string;
          outcome?: string | null;
          posting?: string;
          reached?: string;
          role?: string;
          source?: string;
          stage?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      job_events: {
        Row: {
          application_id: string;
          created_at: string;
          gmail_message: string | null;
          gmail_thread: string | null;
          happened_at: string;
          id: string;
          kind: string;
          subject: string;
        };
        Insert: {
          application_id: string;
          created_at?: string;
          gmail_message?: string | null;
          gmail_thread?: string | null;
          happened_at: string;
          id?: string;
          kind: string;
          subject?: string;
        };
        Update: {
          application_id?: string;
          created_at?: string;
          gmail_message?: string | null;
          gmail_thread?: string | null;
          happened_at?: string;
          id?: string;
          kind?: string;
          subject?: string;
        };
        Relationships: [
          {
            foreignKeyName: "job_events_application_id_fkey";
            columns: ["application_id"];
            isOneToOne: false;
            referencedRelation: "job_applications";
            referencedColumns: ["id"];
          },
        ];
      };
      music_settings: {
        Row: {
          name: string;
          value: NonNullable<Json>;
        };
        Insert: {
          name: string;
          value: NonNullable<Json>;
        };
        Update: {
          name?: string;
          value?: NonNullable<Json>;
        };
        Relationships: [];
      };
      notes: {
        Row: {
          approved: boolean;
          body: string;
          color: string;
          created_at: string;
          id: string;
          name: string;
          user_id: string | null;
          visitor: string | null;
        };
        Insert: {
          approved?: boolean;
          body: string;
          color?: string;
          created_at?: string;
          id?: string;
          name?: string;
          user_id?: string | null;
          visitor?: string | null;
        };
        Update: {
          approved?: boolean;
          body?: string;
          color?: string;
          created_at?: string;
          id?: string;
          name?: string;
          user_id?: string | null;
          visitor?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "notes_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      now_playing: {
        Row: {
          ends_at: string;
          id: boolean;
          song_id: string;
          started_at: string;
        };
        Insert: {
          ends_at: string;
          id?: boolean;
          song_id: string;
          started_at?: string;
        };
        Update: {
          ends_at?: string;
          id?: boolean;
          song_id?: string;
          started_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "now_playing_song_id_fkey";
            columns: ["song_id"];
            isOneToOne: false;
            referencedRelation: "songs";
            referencedColumns: ["id"];
          },
        ];
      };
      playlist_songs: {
        Row: {
          playlist_id: number;
          position: number;
          song_id: string;
        };
        Insert: {
          playlist_id: number;
          position?: never;
          song_id: string;
        };
        Update: {
          playlist_id?: number;
          position?: never;
          song_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "playlist_songs_playlist_id_fkey";
            columns: ["playlist_id"];
            isOneToOne: false;
            referencedRelation: "playlists";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "playlist_songs_song_id_fkey";
            columns: ["song_id"];
            isOneToOne: false;
            referencedRelation: "songs";
            referencedColumns: ["id"];
          },
        ];
      };
      playlists: {
        Row: {
          created_at: string;
          id: number;
          name: string;
        };
        Insert: {
          created_at?: string;
          id?: never;
          name: string;
        };
        Update: {
          created_at?: string;
          id?: never;
          name?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          created_at: string;
          id: string;
          username: string;
        };
        Insert: {
          created_at?: string;
          id: string;
          username: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          username?: string;
        };
        Relationships: [];
      };
      soapbox_posts: {
        Row: {
          body: string;
          created_at: string;
          hidden: boolean;
          id: string;
          images: NonNullable<Json>;
          kind: string;
          media_group_id: string | null;
          place: string | null;
          telegram_message_id: number | null;
          weather: string | null;
        };
        Insert: {
          body: string;
          created_at?: string;
          hidden?: boolean;
          id?: string;
          images?: NonNullable<Json>;
          kind?: string;
          media_group_id?: string | null;
          place?: string | null;
          telegram_message_id?: number | null;
          weather?: string | null;
        };
        Update: {
          body?: string;
          created_at?: string;
          hidden?: boolean;
          id?: string;
          images?: NonNullable<Json>;
          kind?: string;
          media_group_id?: string | null;
          place?: string | null;
          telegram_message_id?: number | null;
          weather?: string | null;
        };
        Relationships: [];
      };
      soapbox_reactions: {
        Row: {
          created_at: string;
          emoji: string;
          post_id: string;
          visitor: string;
        };
        Insert: {
          created_at?: string;
          emoji: string;
          post_id: string;
          visitor: string;
        };
        Update: {
          created_at?: string;
          emoji?: string;
          post_id?: string;
          visitor?: string;
        };
        Relationships: [
          {
            foreignKeyName: "soapbox_reactions_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "soapbox_posts";
            referencedColumns: ["id"];
          },
        ];
      };
      soapbox_settings: {
        Row: {
          name: string;
          value: NonNullable<Json>;
        };
        Insert: {
          name: string;
          value: NonNullable<Json>;
        };
        Update: {
          name?: string;
          value?: NonNullable<Json>;
        };
        Relationships: [];
      };
      song_stats: {
        Row: {
          played_at: string | null;
          plays: number;
          rating: number | null;
          song_id: string;
        };
        Insert: {
          played_at?: string | null;
          plays?: number;
          rating?: number | null;
          song_id: string;
        };
        Update: {
          played_at?: string | null;
          plays?: number;
          rating?: number | null;
          song_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "song_stats_song_id_fkey";
            columns: ["song_id"];
            isOneToOne: true;
            referencedRelation: "songs";
            referencedColumns: ["id"];
          },
        ];
      };
      songs: {
        Row: {
          added_at: string;
          album: string | null;
          artist: string;
          cover: string | null;
          duration_ms: number | null;
          id: string;
          instrumental: boolean;
          lyrics_id: number | null;
          lyrics_offset: number;
          title: string;
          track: number | null;
        };
        Insert: {
          added_at?: string;
          album?: string | null;
          artist: string;
          cover?: string | null;
          duration_ms?: number | null;
          id: string;
          instrumental?: boolean;
          lyrics_id?: number | null;
          lyrics_offset?: number;
          title: string;
          track?: number | null;
        };
        Update: {
          added_at?: string;
          album?: string | null;
          artist?: string;
          cover?: string | null;
          duration_ms?: number | null;
          id?: string;
          instrumental?: boolean;
          lyrics_id?: number | null;
          lyrics_offset?: number;
          title?: string;
          track?: number | null;
        };
        Relationships: [];
      };
      stickies: {
        Row: {
          body: string;
          collapsed: boolean;
          color: string;
          created_at: string;
          height: number;
          id: string;
          updated_at: string;
          user_id: string;
          version: number;
          width: number;
          x: number;
          y: number;
        };
        Insert: {
          body?: string;
          collapsed?: boolean;
          color?: string;
          created_at?: string;
          height?: number;
          id?: string;
          updated_at?: string;
          user_id?: string;
          version?: number;
          width?: number;
          x?: number;
          y?: number;
        };
        Update: {
          body?: string;
          collapsed?: boolean;
          color?: string;
          created_at?: string;
          height?: number;
          id?: string;
          updated_at?: string;
          user_id?: string;
          version?: number;
          width?: number;
          x?: number;
          y?: number;
        };
        Relationships: [
          {
            foreignKeyName: "stickies_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      todos: {
        Row: {
          calendar: string;
          created_at: string;
          done: boolean;
          done_at: string | null;
          due: string | null;
          id: string;
          priority: number;
          title: string;
          updated_at: string;
          user_id: string;
          version: number;
        };
        Insert: {
          calendar?: string;
          created_at?: string;
          done?: boolean;
          done_at?: string | null;
          due?: string | null;
          id?: string;
          priority?: number;
          title: string;
          updated_at?: string;
          user_id?: string;
          version?: number;
        };
        Update: {
          calendar?: string;
          created_at?: string;
          done?: boolean;
          done_at?: string | null;
          due?: string | null;
          id?: string;
          priority?: number;
          title?: string;
          updated_at?: string;
          user_id?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "todos_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      chat_activity: {
        Args: Record<PropertyKey, never>;
        Returns: {
          last_at: string;
          room: string;
        }[];
      };
      chat_can_read: { Args: { target: string }; Returns: boolean };
      chat_can_write: { Args: { target: string }; Returns: boolean };
      is_owner: { Args: Record<PropertyKey, never>; Returns: boolean };
      job_hunt_totals: { Args: Record<PropertyKey, never>; Returns: Json };
      moderation_check: { Args: { p_secret: string }; Returns: boolean };
      moderation_register: { Args: { p_url: string }; Returns: undefined };
      music_play: {
        Args: { p_song: string };
        Returns: {
          ends_at: string;
          id: boolean;
          song_id: string;
          started_at: string;
        };
        SetofOptions: {
          from: "*";
          to: "now_playing";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      music_stop: { Args: Record<PropertyKey, never>; Returns: undefined };
      my_reactions: {
        Args: Record<PropertyKey, never>;
        Returns: {
          emoji: string;
          post_id: string;
        }[];
      };
      my_recovery_email: { Args: Record<PropertyKey, never>; Returns: string };
      notes_left: { Args: Record<PropertyKey, never>; Returns: number };
      now_playing_position: {
        Args: Record<PropertyKey, never>;
        Returns: {
          elapsed_ms: number;
          remaining_ms: number;
          song_id: string;
        }[];
      };
      rate_song: { Args: { p_rating: number; p_song: string }; Returns: undefined };
      recovery_check: { Args: { p_token_hash: string }; Returns: string };
      recovery_consume: {
        Args: { p_token_hash: string };
        Returns: {
          user_id: string;
          username: string;
        }[];
      };
      recovery_request: { Args: { p_token_hash: string; p_username: string }; Returns: string };
      save_playlist: { Args: { p_name: string; p_songs: string[] }; Returns: number };
      set_recovery_email: { Args: { p_email: string }; Returns: undefined };
      soapbox_add_images: {
        Args: {
          p_body: string;
          p_group: string;
          p_images: Json;
          p_kind: string;
          p_message: number;
          p_place: string;
          p_weather: string;
        };
        Returns: {
          created: boolean;
          id: string;
        }[];
      };
      song_limit: { Args: Record<PropertyKey, never>; Returns: number };
      song_played: { Args: { p_song: string }; Returns: undefined };
      username_available: { Args: { name: string }; Returns: boolean };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
